services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo
      - redis
