version: '3'
services:
  mongo:
    image: mongo:6
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo
      - redis
