name: Backend CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'intern-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('intern-backend/**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: intern-backend
        run: npm ci

      - name: Run tests
        working-directory: intern-backend
        run: npm test

      - name: Build project
        working-directory: intern-backend
        run: npm run build

      - name: Capture commit SHA
        id: commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (for git ref)
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy backend only
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          APP_DIR: ${{ secrets.BACKEND_PATH }}
          GIT_REF: ${{ needs.build.outputs.sha }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd $APP_DIR_
